resources:
- name: src
  type: git
  source:
    uri: git@github.com:SUSE/stampy.git
    branch: master
    private_key: {{github-private-key}}

- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/stampy-ci.git
    branch: master
    private_key: {{github-private-key}}

- name: s3.stampy-linux
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    endpoint: {{s3-endpoint}}
    secret_access_key: {{s3-secret-key}}
    bucket: stampy
    regexp: stampy-(.*\.g.*)\.linux.amd64\.tgz
    private: true

- name: s3.stampy-darwin
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    endpoint: {{s3-endpoint}}
    secret_access_key: {{s3-secret-key}}
    bucket: stampy
    regexp: stampy-(.*\.g.*)\.darwin.amd64\.tgz
    private: true

jobs:
- name: vet
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: src
      trigger: true
  - task: vet
    file: ci/tasks/vet.yml

- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: ci
      trigger: true
  - task: tools
    file: ci/tasks/tools.yml
  - task: test
    privileged: true
    file: ci/tasks/test.yml

- name: lint
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: ci
      trigger: true
  - task: tools
    file: ci/tasks/tools.yml
  - task: lint
    file: ci/tasks/lint.yml

- name: format
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: ci
      trigger: true
  - task: tools
    file: ci/tasks/tools.yml
  - task: format
    file: ci/tasks/format.yml

- name: dist
  plan:
  - aggregate:
    - get: src
      passed: [vet, lint, format, test]
      trigger: true
    - get: ci
      passed: [vet, lint, format, test]
      trigger: true
  - task: tools
    file: ci/tasks/tools.yml
  - task: build
    file: ci/tasks/build.yml
  - task: dist
    file: ci/tasks/dist.yml
  - put: s3.stampy-linux
    params:
      file: dist/stampy-*linux-*.tgz
      acl: public-read
  - put: s3.stampy-darwin
    params:
      file: dist/stampy-*darwin-*.tgz
      acl: public-read
