---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: golang
   tag: '1.7.3'

inputs:
  - name: src
    path: src/github.com/SUSE/stampy
  - name: ci
  - name: tools
    path: bin
  - name: build
outputs:
  - name: dist
    path: stampy
run:
  path: ci/tasks/dist.sh
