--- 
platform: linux
image_resource:
 type: docker-image
 source:
   repository: golang
   tag: '1.7.3'
inputs:
  - name: src
    path: src/github.com/SUSE/stampy
  - name: src-ci
  - name: tools
    path: bin
run:
  path: src-ci/tasks/test.sh
