---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: golang
   tag: '1.7.3'
inputs:
  - name: src
    path: src/github.com/hpcloud/stampy
  - name: src-ci
run:
  path: src-ci/tasks/vet.sh
